"""empty message

Revision ID: 1e579178b58f
Revises: 7a4cd3ac931
Create Date: 2014-04-19 19:54:28.245811

"""

# revision identifiers, used by Alembic.
revision = '1e579178b58f'
down_revision = '7a4cd3ac931'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    ### end Alembic commands ###
